export enum fixturesIncludes {
  sport = 'sport',
  round = 'round',
  stage = 'stage',
  group = 'group',
  aggregate = 'aggregate',
  league = 'league',
  seasoncoaches = 'seasoncoaches',
  tvStations = 'tvStations',
  venue = 'venue',
  state = 'state',
  weatherReport = 'weatherReport',
  lineups = 'lineups',
  events = 'events',
  timeline = 'timeline',
  comments = 'comments',
  trends = 'trends',
  statistics = 'statistics',
  periods = 'periods',
  participants = 'participants',
  oddspremiumOdds = 'oddspremiumOdds',
  inplayOdds = 'inplayOdds',
  prematchNews = 'prematchNews',
  metadata = 'metadata',
  sidelinedpredictions = 'sidelinedpredictions',
  referees = 'referees',
  formations = 'formations',
  ballCoordinates = 'ballCoordinates',
  scores = 'scores',
}

export type FixtureInclude = keyof typeof fixturesIncludes;
